# Generated by Django 5.1.15 on 2026-02-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_user_id",
            field=models.CharField(
                blank=True,
                help_text="User ID in external time manager system",
                max_length=100,
                null=True,
            ),
        ),
    ]
