# Generated by Django 5.1.15 on 2026-02-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Company ID in external time manager system",
                max_length=100,
                null=True,
            ),
        ),
    ]
