# Generated by Django 4.1.5 on 2023-01-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_worklocation_alter_customuser_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklocation',
            name='teleworking',
        ),
        migrations.AddField(
            model_name='worklocation',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Remote location'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='worklocations',
            field=models.ManyToManyField(blank=True, related_name='user_worklocations', to='accounts.worklocation'),
        ),
    ]
