# Generated by Django 3.2.10 on 2022-02-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220201_1945'),
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signing',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='signing',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='signing',
            name='description',
            field=models.TextField(blank=True, verbose_name='Signing description'),
        ),
    ]
