# Generated by Django 4.1.5 on 2023-01-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_worklocation_teleworking_worklocation_remote_and_more'),
        ('workday', '0002_auto_20220201_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='worklocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.worklocation'),
        ),
    ]
